### ISSUE TITLE
pick-a-role

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fs-dapp#2]
For users that connect to the chain with their wallet, we want to know with which role they want to join, so we can display their front-end needs.

Display a selection of roles users can choose from.

**Comment by cuteolaf** [comment]
https://github.com/Fair-Squares/fs-dapp/pull/5

**Comment by cuteolaf** [comment]
- [x] Show the list of available roles
- [x] Request a role
- [ ] If a user has requested a role that needs approval from `SERVICER`s, show it in the role section.
- [ ] Role approval page for a `SERVICER`
